"""add_validation_config_to_companies

Revision ID: 0aaae2085397
Revises: f4a5b6c1d2e3
Create Date: 2026-06-09 15:56:55.639062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaae2085397'
down_revision: Union[str, Sequence[str], None] = 'f4a5b6c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('validation_config', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_dah_id'), table_name='driver_accounts_history')
    op.create_index(op.f('ix_driver_accounts_history_id'), 'driver_accounts_history', ['id'], unique=False)
    op.drop_index(op.f('ix_pt_id'), table_name='peibo_transactions')
    op.drop_index(op.f('ix_pt_tracking_code'), table_name='peibo_transactions')
    op.create_index(op.f('ix_peibo_transactions_id'), 'peibo_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_peibo_transactions_tracking_code'), 'peibo_transactions', ['tracking_code'], unique=True)
    op.drop_index(op.f('ix_pwe_id'), table_name='peibo_webhook_events')
    op.create_index(op.f('ix_peibo_webhook_events_id'), 'peibo_webhook_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peibo_webhook_events_id'), table_name='peibo_webhook_events')
    op.create_index(op.f('ix_pwe_id'), 'peibo_webhook_events', ['id'], unique=False)
    op.drop_index(op.f('ix_peibo_transactions_tracking_code'), table_name='peibo_transactions')
    op.drop_index(op.f('ix_peibo_transactions_id'), table_name='peibo_transactions')
    op.create_index(op.f('ix_pt_tracking_code'), 'peibo_transactions', ['tracking_code'], unique=True)
    op.create_index(op.f('ix_pt_id'), 'peibo_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_driver_accounts_history_id'), table_name='driver_accounts_history')
    op.create_index(op.f('ix_dah_id'), 'driver_accounts_history', ['id'], unique=False)
    op.drop_column('companies', 'validation_config')
    # ### end Alembic commands ###
